### ISSUE TITLE
destroy method memory leak

### ISSUE THREAD

**Issue by jmvtrinidad** [DataTables/DataTables#669] opened 2015-09-17 09:57 UTC
I use knockout generator from yeoman, developed by steve sanderson for this example.

This is the initial memory alocated for `jQuery DataTable` on first load for this page.

[![enter image description here][1]][1]

After viewing another page it execute this part of code:

    // This runs when the component is torn down. Put here any logic necessary to clean up,
    // for example cancelling setTimeouts or disposing Knockout subscriptions/computeds.
    Table.prototype.dispose = function () { 
        this.table.destroy(true);
    };

The `Table` should be disposed already along with that particular page but it is not GC'd. As seen in the next picture.

[![enter image description here][2]][2]

I think the use of `.destroy()` method from `jQuery DataTable` cause the memory leaks. If I removed `this.table.destroy()` in `dispose`, the `Table` is GC'd and table element is not GC'd, I think the element has reference to the `jQuery DataTable` object. As seen in the next picture. That's why the element is not disposed properly.

[![enter image description here][3]][3]

Any suggestion to dispose properly

  [1]: http://i.stack.imgur.com/365WG.png
  [2]: http://i.stack.imgur.com/IDXBf.png
  [3]: http://i.stack.imgur.com/bNVMP.png

**Comment by DataTables** [comment] 2015-09-17 13:37
Thank you for posting this. If you were to create and destroy the table without knockout generator (which I haven't actually come across before), does it still leak memory then? My first suggestion would be to find if the leak is being caused by DataTables or the external software.

**Comment by jmvtrinidad** [comment] 2015-09-18 03:19
Hi,
In my findings, on 3rd image, when i remove the call of `destroy()` in `dispose()` method the `Table` object is able to GC'd, but the HTMLTableElement is not GC'd. So I think it is cause by calling `destroy()` method.
The whole object where the call of `destroy()` method was not able to GC'd, I think there's something in `destroy()` that holds a value.
Thanks for replying.

**Comment by DataTables** [comment] 2015-09-18 08:05
If you are able to link to a test case showing the issue that would be helpful.

**Comment by jmvtrinidad** [comment] 2015-09-18 09:26
I can give you the code, if you like.

**Comment by DataTables** [comment] 2015-09-18 09:30
Just a link to a test case showing the issue would be perfect.

**Comment by jmvtrinidad** [comment] 2015-09-18 10:40
I only run it in my local machine and also I test it manually and profile it using google chorme.,.

**Comment by DataTables** [comment] 2015-09-18 10:43
Okay thanks for the update. There isn't much help I can offer until there is a test case I can run and debug. Unfortunately I've not got enough free time to try and set up an example using this structure myself.

**Comment by DataTables** [comment] 2016-02-03 12:18
Going to close this issue for now. If you are able to put up a test case that I can profile, please reopen the issue with the link.

**Closed by DataTables** 2016-02-03 12:18 UTC
