### ISSUE TITLE
destroy property doesn't work in the same manner as destroy()

### ISSUE THREAD

**Issue by smasala** [DataTables/DataTables#945] opened 2017-06-29 15:17 UTC
In both examples click the button `toggle Position` (bottom) which adds and removes the `Position` column and redraws the table.

Working example with `destroy()`: 
http://jsfiddle.net/j81a9y8c/

The following example duplicates the last column for some reason:
http://jsfiddle.net/9rona6mh/

**Comment by DataTables** [comment] 2017-06-30 08:37
Using the `destroy` property doesn't actually remove the old table from the document. It does call the internal destroy method the same way as `destroy()` does, but in your first example you have `$('#example').empty();` which makes all the difference.

Without that you would see the same effect since the original set of columns is still present.

This is actually expected behaviour at the moment - the `destroy` option should not remove the data from the document. Although I can see this could be a bit confusing. I'll have a think about how to improve this, but going to close this one as worked as expected just now.

**Closed by DataTables** 2017-06-30 08:37 UTC

**Comment by smasala** [comment] 2017-06-30 08:42
@DataTables what would be great is if the `.empty()` wasn't needed at all :+1: :)
