### ISSUE TITLE
DataTables doesn't calculate column width after hidden columns

### ISSUE THREAD

**Issue by epitaphmike** [DataTables/DataTables#633] opened 2015-08-18 20:31 UTC
DataTables 1.10.8 has an issue calculating the column widths of columns preceding a hidden column. Looping through the columns to set the width based on the header works fine until the loop hits a hidden column. All visible columns after the hidden column get a width of 0px.

Between PIM and +/- columns there are 2 hidden columns in the dataObject.

![image](https://cloud.githubusercontent.com/assets/677832/9341881/8c9e0f28-45c6-11e5-8061-fbb58a0cb328.png)

**Comment by DataTables** [comment] 2015-08-19 09:26
Could you possibly link to a test case showing the issue please. I've just tried to reproduce the problem [here](http://live.datatables.net/bafiveso/1/edit) but wasn't able to do so.

**Comment by DataTables** [comment] 2015-08-19 09:59
Cross post [from the DataTables forums](https://www.datatables.net/forums/discussion/29549/).

**Comment by nddery** [comment] 2015-08-20 16:29
Not sure if this is exactly the @epitaphmike problem but we're having problems with columns width calculation when showing back columns and the "scrollX" option. I've created a fiddle here.

http://live.datatables.net/bafiveso/2

If you toggle all metrics but one off, and then start to toggle them back in, you'll see that the width is not recalculated correctly.

**Comment by epitaphmike** [comment] 2015-08-20 18:58
Yes @nddery This is the issue we are having as well. There is a direct correlation between the number of columns hidden to the number of columns with a width set to 0px. If you hide 3 columns, the last 3 visible columns have width set to 0px. 

![image](https://cloud.githubusercontent.com/assets/677832/9392622/c9f081b8-474b-11e5-9f54-7b59a9d526b6.png)

![image](https://cloud.githubusercontent.com/assets/677832/9392647/e80ebac0-474b-11e5-8ae2-8dbf71145e23.png)

**Comment by nddery** [comment] 2015-08-20 20:31
I am not so sure about the direct correlation. Here, with 4 columns hidden, only the last 2 visible columns had widths of 0.

![screen shot 2015-08-20 at 4 03 29 pm](https://cloud.githubusercontent.com/assets/610207/9394234/566f02e6-4755-11e5-925a-386d6a70da07.png)

**Comment by epitaphmike** [comment] 2015-08-20 23:24
@nddery That is because you are showing the initial columns 1-4, 7 and 10
If you notice, 1-4 have widths, while 7 and 10 are 0's The bug is working from the last column in.
Hide 1-4 and you see 4 with width's of 0, then 2-5, 3-6 all the same, 4 0's
Hide 4-7 and you only have 3 remaining columns 8-10, which are all set to 0's now.
I home that makes sense.

**Comment by nddery** [comment] 2015-08-21 16:41
@epitaphmike Yes, that make sense now.

We came up with a "workaround" for this. We setup the table like so:

```js
this.table = $table.DataTable({
  autoWidth: false,
  data: this.dataset,
  columns: this.columns,
  scrollX: true
});
```

Note that we set `autoWidth: false` and use `scrollX: true` - maybe this affects things in a way I don't know/understand. Without `scrollX: true`, no width styles are applied (as I would of assumed from `autoWidth: false`), but columns are equally wide.

On initial load, all table header cell have a width of 0 - which does not seems to impact the visuals. However, upon hiding columns and showing them back, all headers cells widths are recalculated and no cells have a width of 0.

We added a style of `width: 100%!important` on the table itself, which somehow, force the recalculation of the table width.

[See this fiddle here](http://live.datatables.net/yefuqule/1/).

**Comment by DataTables** [comment] 2015-08-24 15:06
Hi,

Thanks for the comments on this and sorry for my delay in replying.

I've just been trying to reproduce this effect with the above code, but I'm still not quite getting it I'm afraid. Here is what I've tried based on your comments above @epitaphmike:

1. Load http://live.datatables.net/royawohi/1/edit
2. Hide columns 1-4 - all columns have a sensible width
3. Put them back in one by one - all columns have sensible widths

I've also tried based on

> That is because you are showing the initial columns 1-4, 7 and 10

Adding 

```js
    if ( i === 5 || i === 6 || i === 8 || i === 9 ) {
      columns.push({ title: 'Columns ' + i, visible: false });
    }
    else {
      columns.push({ title: 'Columns ' + i });
    }
```

And then toggling the column visibility. But still the columns have the correct widths and I've not seen one with 0px yet.

Could you give me step by step instructions how to reproduce the issue so I can look into it? I'm hoping to do a new release of DataTables at the end of the week, so it would be great to be able to address this in it.

**Comment by nddery** [comment] 2015-08-24 15:27
Hi @DataTables,

The steps you provided seems right. I found it is easier to spot the problem when you viewport is large enough. It may be easier to test this (visually, the actual problem is still present no matter which width your viewport is) with only the "Output" panel visible and your browser window set to be fullscreen.

1. Load http://live.datatables.net/royawohi/1/edit
2. Ensure only the "Output" panel is visible
3. Hide columns 1, 2 and 3
  - You should now be able to visually see inconsistency between the columns width
4. Inspect the table header cells
  - Notice that the 3 last cells have `widths: 0px`
    
    ![screen shot 2015-08-24 at 11 23 00 am](https://cloud.githubusercontent.com/assets/610207/9444066/893d590c-4a52-11e5-96c5-9cb19fca34d8.png)
5. (extra) Show columns 1, 2 and 3
  - The inconsistency between columns width is still visible

    ![screen shot 2015-08-24 at 11 24 27 am](https://cloud.githubusercontent.com/assets/610207/9444099/b89c5842-4a52-11e5-9bfc-6f10d274cd65.png)

**Comment by DataTables** [comment] 2015-08-24 15:31
I've set my browser window to use 1920px width with the inspector attached to the bottom of the window.

If I hide columns 1, 2 and 3 I see no visual misalignment between the columns and the column widths appear to be sensible:

![screen shot 2015-08-24 at 16 26 17](https://cloud.githubusercontent.com/assets/278219/9444225/54b47c26-4a7d-11e5-9fd6-4bfc512d3f01.png)

I think I'm missing something!

**Comment by nddery** [comment] 2015-08-24 15:38
@DataTables this seems to only happens on Mac OSX. Tested so far on Chrome 44 on Windows (no problem) and Chrome 44 on Max (has problems) - however, from the look of your screenshot, you seem to be on OSX ?

**Comment by DataTables** [comment] 2015-08-24 15:40
Yup - Chrome 44.0.2403.155 Mac.

**Comment by nddery** [comment] 2015-08-24 15:44
Do you happen to be on Mountain Lion ? Problem seems to only occurs on OSX 10.9 and above.

**Comment by DataTables** [comment] 2015-08-24 15:50
10.9.5.

I've just fired up a different machine with 10.10 and see the problem with Chrome 43.0.2357.124. Very tempted to update Chrome to 44 on that machine and see if the problem disappears, but it does, I won't be able to debug this!

I wonder if this is looking like a Chrome 43 issue.

**Comment by nddery** [comment] 2015-08-24 15:55
That is all bizarre. I can reproduce this problem every time on 10.9.5, Chrome 44. Mostly tested in BrowserStack so no extensions loaded and the problem also happens in Incognito on my own computer (to rule out extensions problems).

**Comment by DataTables** [comment] 2015-08-24 16:15
On the plus side we aren't all going crazy :-).

I can reproduce this with a local test case on 10.10 with Chrome 43. I'll post back when I've dug into it a bit more.

**Comment by DataTables** [comment] 2015-08-25 11:17
I think I've got it - it depends on if the computer is set to have Apple's hidden scrollbars or not. It the scrollbars are hidden (i.e. have zero width) then DataTables is dropping into its IE6/7 mode... Will post back again shortly, hopefully with a fix.

**Comment by nddery** [comment] 2015-08-25 12:52
Just tested with the settings set to "Always show scrollbar" and the problem is indeed not present. Great catch!

**Comment by epitaphmike** [comment] 2015-08-25 13:10
Very nice. I've come across problems like this in the past with different
libraries. Nicely done and very appreciated.

**Comment by DataTables** [comment] 2015-08-25 13:24
I like this kind of bug:

* Awesome contributions (thanks for the help!)
* Nice little challenge to find it
* The fix removes code (saved 163 bytes from the min version of DataTables)
* The fix improves performance (I only perform the browser calculations involved here once per page  now)

The fixes that Github handily referenced above are now in the [DataTables nightly](http://datatables.net/download/nightly#DataTables) and will be included in the 1.10.9 release :-)

**Closed by DataTables** 2015-08-25 13:24 UTC

**Comment by nddery** [comment] 2015-08-25 13:34
Amazing work! Thanks for all your work on that! Will patiently await 1.10.9 :)

**Comment by sangelone** [comment] 2016-04-13 23:16
I still see this behavior under a specific circumstance. Only on Chrome under OS X and only with "Always Show Scrollbar" disabled, if you have a column after a hidden one **with no text in the header**, it will always be set to a width of 0px.

**Comment by DataTables** [comment] 2016-04-14 08:47
I'm not able to see that issue: http://live.datatables.net/nusopina/1/edit . Can you link to a page showing the problem please.

**Comment by sangelone** [comment] 2016-04-14 18:21
You're right. I set "visible": false to a column before the one with no header text and it works fine on the nightlies now. I was observing it on 1.10.10.

**Comment by istrau3** [comment] 2016-11-03 15:53
@DataTables I am having this problem. Basically, I have a column definition with width: '20%' (which works fine - the column is displayed with the right width). However, if I set the visibility to false and back to true, it loses its hardcoded visibility and is sized to 0px (in the html source). I am using version 1.10.12 on chrome 54.0.2840.87 on windows 10.

**Comment by DataTables** [comment] 2016-11-03 15:56
Can you link to a page showing the issue please.

**Comment by istrau3** [comment] 2016-11-03 16:51
@DataTables Somehow I can't seem to reproduce this issue. I suppose you can just ignore until I succeed in reproducing.

**Comment by kodecount** [comment] 2017-01-23 18:09
I was able to reproduce when having a empty column in my table with these settings `"bProcessing": true, "order": [[0, "asc"]], "bInfo" : false, "searching": false` . Also using version 1.10.7. Also discussed here: https://github.com/wet-boew/wet-boew/issues/7854

**Comment by DataTables** [comment] 2017-01-23 20:30
If you could link to a test case that I can debug that would be great.
