### ISSUE TITLE
How to change Language after Initialisation?

### ISSUE THREAD

**Issue by SunboX** [DataTables/DataTables#536] opened 2015-04-13 07:53 UTC
Hi,

I want to change the Language (object) used by DataTables **after** it was initialized. I can't find any docs or anything on Google / Stackoverflow about this. How can I change the Language afterwards?

**Comment by DataTables** [comment] 2015-04-13 08:22
You wouldn't be able to find anything about this as it currently isn't possible. Sorry! I'll mark this as a feature bug, but it isn't something that I'm planning to work on in the immediate future as there are other things I am working on.

**Comment by SunboX** [comment] 2015-04-13 09:13
Oh, that's sad. But thanks for your feedback!

For future, would be cool if we just could use the [Web L10n API](https://developer.mozilla.org/en-US/docs/Web/API/L10n_API). So the only thing DataTables has to implement are `data-l10n-id=""` attributes. Like so:

```html
<div 
    aria-live="polite" 
    role="status" 
    id="vacation-list_info" 
    class="dataTables_info" 

    data-l10n-id="info" 
    data-l10n-args='{ "start": 1, "end": 13, "total": 57 }'

>Showing 1 to 13 of 57 entries</div>
```

Then if we wan't to "live" switch the language, we can just do a:
```js
$('#example').DataTable();

navigator.mozL10n.ready( function() {
    navigator.mozL10n.localizeNode($('#example'));
});
navigator.mozL10n.requestLocales('de-DE');
```

Btw, `navigator.mozL10n` is equivalent to `document.l10n` using [L20n](http://l20n.org/).

**Comment by DataTables** [comment] 2015-04-13 09:20
While the parameter names are slightly different, you can use `data-*` attributes to the the options for a DataTable, include the language options: http://datatables.net/manual/options#HTML-5-data-attributes .

**Comment by SunboX** [comment] 2015-04-13 12:22
I think that won't work for auto-generated stuff like the Scroller Plugin?

An alternative to the `data-l10n-id=""` attributes could be a `update()` function:

```js
$('#example').data('DataTable').update({
    language = {
        // ...
        info: 'Zeige _START_ bis _END_ von _TOTAL_ Einträge',
        // ...
    }
});
```

**Comment by DataTables** [comment] 2015-04-13 12:32
Correct - Scroller will not work with that structure at the moment.

The concern with dynamically changing the language strings is that it will include extra code into the core library - which is already about as large as I want to make it. iw ill need to make saving else where before this ability can be included.

**Comment by PeterDaveHello** [comment] 2016-06-07 12:53
hmmmm ... is there any news about l10n/i18n? It'll be a very nice feature! Thanks.

**Comment by DataTables** [comment] 2016-06-07 14:05
This issue will be updated when there is a change, but it is unlikely dynamic i18n options will be coming soon.

**Comment by DataTables** [comment] 2016-09-28 20:48
Closing as a duplicate of #264.

**Closed by DataTables** 2016-09-28 20:48 UTC
Labels: Feature
