### ISSUE TITLE
Reset ordering part of orderSequence

### ISSUE THREAD

**Issue by Stadly** [DataTables/DataTables#829] opened 2016-05-30 10:10 UTC
It would be nice if sorting could easily be reset, showing the rows in their original order.

What I imagine, is to extend the `columns.orderSequence` option to support a third value, for example `null` or `""` (the empty string), which means to disable sorting.

`"orderSequence": [ "asc", "desc", null ]` would mean that, by clicking on a column header, the rows will be ordered first ascending, then descending, and lastly be shown in their original order.

Such an ordering sequence is used for example by Spotify. When sorting a playlist by clicking on a column, the tracks are shown ascending, descending and then in their playlist order.

**Comment by DataTables** [comment] 2016-05-30 11:10
Thanks for the suggestion. However, this is a duplicate of #526.

**Closed by DataTables** 2016-05-30 11:10 UTC
