### ISSUE TITLE
Columns.data Issue: Setting cell values more than once

### ISSUE THREAD

**Issue by strang91** [DataTables/DataTables#638] opened 2015-08-19 09:19 UTC
Re-posting the issue from https://www.datatables.net/forums/discussion/25846 so it can be better tracked on github.

It seems columns.data **is setting each cell in a column more than once**. I hope this isn't expected behavior as I expect each cell should be set only once.

A test case showing this issue is shown in the link below: http://live.datatables.net/sosufero/1/edit

The result is shown in the console not in the output. As you can see in the example above, the cell value is being logged more than once in the **set case**.

You can compare the above case (1.10.8) with the one below (1.10.2) http://live.datatables.net/sosufero/3/edit

As you can see the results in the console is different.

**Comment by DataTables** [comment] 2015-08-19 09:24
No it isn't expected behaviour. It is a bug. i will look into it as soon as I get a chance to do so. Somewhat overwhelmed at the moment, so not entirely sure when, but hopefully soon.

**Comment by DataTables** [comment] 2015-08-25 14:13
This has [now been fixed](https://github.com/DataTables/DataTablesSrc/commit/2b868a5800511). It was basically a case of an old hack resulting in the duplicate calls when a DOM node is given. The fix will be in 1.10.9. Thanks!

**Comment by strang91** [comment] 2015-08-25 16:46
Thanks.

**Comment by strang91** [comment] 2015-08-26 19:06
Just to let you know. The first row is still being processed twice. http://live.datatables.net/sosufero/6/edit
Result in console.

**Comment by DataTables** [comment] 2015-08-26 19:47
Thank you for the test case - it looks like the `set` handler is being called twice for the first row in the table. I'm not sure why that is happening.

**Comment by DataTables** [comment] 2015-08-27 09:54
Thanks - fixed now :-)

**Closed by DataTables** 2015-08-27 09:54 UTC

**Comment by strang91** [comment] 2015-08-27 10:36
Fix confirmed. Thanks a bunch.
