### ISSUE TITLE
ajax.data not working since 1.10.5 ? 

### ISSUE THREAD

**Issue by InfinityWebMe** [DataTables/DataTables#552] opened 2015-05-02 15:30 UTC
Hello, 

since the version 1.10.5, ajax.data ( https://datatables.net/reference/option/ajax.data ) doesn't work anymore :-/

Any idea what happens ? 

Here my code for example ( work perfectly on 1.10.4 ) : 

```
defaultOptionsDatatable.ajax = {
            url: $datatable.attr('data-ajax'),
            data: function (d) {
                console.log('test');
                var idTable = $datatable.attr('id');

                d.filter = dtData;

                $('.dataTables_navbar[data-table=' + idTable + ']').each(function () {


                    var val = '';
                    var column = $(this).attr('data-key');
                    var columnInt = parseInt(column);

                    if ($(this).is('ul')) {
                        val = $(this).find('li.selected').attr('data-value');
                    } else {
                        val = $(this).val();
                    }

                    if (!isNaN(columnInt)) {
                        if (!(typeof d.columns[columnInt] === "undefined")) {
                            d.columns[columnInt].search.value = val;
                        } else {
                            d.columns.push({
                                'data': columnInt,
                                'name': "",
                                'orderable': false,
                                'search': {
                                    'regex': false,
                                    'value': val
                                },
                                'searchable': true
                            });
                        }
                    } else {
                        d.filter[column] = val;
                    }

                });
            }
        };
```

Thanks a lot for helping :+1:

**Comment by DataTables** [comment] 2015-05-02 16:06
Can you link to a test case showing the issue please.

**Comment by DataTables** [comment] 2015-05-03 12:58
For information, I've just put together a little test case myself here: http://live.datatables.net/riqajiqa/1/edit . You will be able to see that `ajax.data` does appear to be working that. I'd need a test case showing it not working please.

**Comment by InfinityWebMe** [comment] 2015-05-03 16:45
Hello, 

i give you a test case tomorrow, sorry to late reply :-/

**Comment by InfinityWebMe** [comment] 2015-05-20 08:09
Sorro fo the delay, but, for now, i can not repdouce the issue out of my app :-/

**Comment by DataTables** [comment] 2015-05-20 08:39
No worries. I'm afraid I can't offer much help without being able to see the issue though. Are you okay if I close this until you or anyone else has a test case available showing the issue then?

**Comment by InfinityWebMe** [comment] 2015-05-20 10:48
I'm okay ;)

**Closed** 2015-05-20 10:51 UTC

**Comment by BenMesirowCorista** [comment] 2015-10-09 15:08
I am having a similar issue since upgrading from 1.10.4 to 1.10.9 (tested with all versions between 1.10.4 and 1.10.9 and discovered that the issue was after upgrading to 1.10.5 and higher).  My code worked perfectly before upgrading, and now for some reason DataTable tries to convert the value of the "ajax" to a string and put it in the url as [object%20Object] instead of treating it as a regular old JavaScript object.  Here is the options object passed to DataTable:

{serverSide: true, processing: true, ajax{url: "/my_path", data: myDataFunc}}

**Comment by DataTables** [comment] 2015-10-09 15:15
Please link to a test case showing the issue.

**Comment by BenMesirowCorista** [comment] 2015-10-09 15:36
Can't seem to reproduce outside my code :(
