### ISSUE TITLE
Dev Question // permit .data & .render to return DOM element

### ISSUE THREAD

**Issue by cdaringe** [DataTables/DataTables#489] opened 2015-02-04 23:08 UTC
Hi Allan:
I haven't dug deep into this yet, but have at least opened and peered at the source.  I'm interested in allowing .data to return a DOM element vs a 'string', basic obj, or primitive.

# Problem Statement
Often, I want to generate a DOM element, bind event listeners to it, then put it into the table.
I can pursue alternatives, such as generate the table, then scour it to add event listeners, however this is excess overhead compared to the proposed.

# Solution/Objective
Permit .data and .render to "render" a DOM element if provided.  Update `._fnSetObjectDataFn` and ... ? ... per your insights if you find it worthwhile.

### PS
https://github.com/DataTables/DataTables/blob/master/media/js/jquery.dataTables.js#L1306
For efficiency sake, to prevent the creation of a new function on every cell with no data, would it be OK instead to pass a singleton no-op function?

```js
    ...
	function _fnSetObjectDataFn( mSource )
	{
		if ( $.isPlainObject( mSource ) )
		{
			/* Unlike get, only the underscore (global) option is used for for
			 * setting data since we don't know the type here. This is why an object
			 * option is not documented for `mData` (which is read/write), but it is
			 * for `mRender` which is read only.
			 */
			return _fnSetObjectDataFn( mSource._ );
		}
		else if ( mSource === null )
		{
			/* Nothing to do when the data source is null */
			return noop; // ==> vs function () { }, pass constant noop pointer
		}
... jump to end of file ...
	return $.fn.dataTable;
}));

var noop = function () {}; // define noop, vs many no-op functions

}(window, document));

**Comment by cdaringe** [comment] 2015-02-04 23:14
Also, I know you have some unit tests somewhere, at least that I saw in responsive.  Are these 8 the whole shaboodle in `DataTables/media/unit_testing`?  I didn't see remarks in `Contributing.md`.

**Comment by DataTables** [comment] 2015-02-05 11:29
Hi,

you might be interested in the discussions in #435, #429 and #425 which discuss this topic. In short, currently returning a node is not supported as you realise, but it is something I will consider for a future release. Likely it will require the `columns.render` option to check for the `display` type and return a node. All other options would need to return a string / number / etc (e.g. return the data you want to be used for filtering, sorting, etc since you wouldn't want to use a node for those operations).

Unit tests are held in the src repo ( https://github.com/DataTables/DataTablesSrc/tree/master/tests ) (I should remove them from here). The whole testing framework is in bad need of a serious upgrade. I hope to get a chance to do that later this year.

Going to close this issue as a duplicate of the others linked to above.

**Closed by DataTables** 2015-02-05 11:29 UTC

**Comment by cdaringe** [comment] 2015-02-05 16:57
Ah, thanks for the good word!
