### ISSUE TITLE
csv button giving error on console

### ISSUE THREAD

**Issue by bgrayburn** [DataTables/DataTables#673] opened 2015-09-21 21:55 UTC
Hey, Thanks for this awesome library! I'm instantiating a datatable using the buttons extension and getting the following error on the console when that button is clicked:

    Error: a[e].replace is not a function
    TypeError: a[e].replace is not a function
        at i (buttons.html5.min.js?ba315e4f178f1329ec9e90aedf7d3d1156fb9bb5:7)
        at B (buttons.html5.min.js?ba315e4f178f1329ec9e90aedf7d3d1156fb9bb5:7)
        at Object.n.ext.buttons.csvHtml5.action (buttons.html5.min.js?ba315e4f178f1329ec9e90aedf7d3d1156fb9bb5:13)
        at HTMLAnchorElement.<anonymous> (dataTables.buttons.min.js?7b8b315ccd79137061a5c682776a47eac9033fec:13)
        at HTMLAnchorElement.jQuery.event.dispatch (jquery.js:4665)
        at HTMLAnchorElement.jQuery.event.add.elemData.handle (jquery.js:4333)

any help appreciated, best

**Comment by DataTables** [comment] 2015-09-22 08:19
Can you try the version in this repo please, if you haven't already. If you have and it is still causing issues, please link to a test case showing the issue.

**Comment by JosKrause** [comment] 2015-10-04 14:05
I believe this 'error' situation is being triggered when DataTables is configured to hide certain columns, then when pressing the CSV button, it will iterate through all the columns requested through the data property and it will iterate over a column that is not visible.

So the quick answer would be to ensure that your configuration is aware of these hidden columns and adjust the initialization part of your buttons:

```javascript
                exportOptions: {
                    columns: ':visible'
                }
```

You need to add this to the *extend* part of the CSV button like so:

```javascript
                    {
                        extend: 'csv',
                        exportOptions: {
                            columns: ':visible'
                        }
                    }
```

Hope this helps,

**Comment by mahlonsmith** [comment] 2015-10-07 00:25
I just experienced the same problem (with DT 1.10.9) -- tracked it down to a member of my returned ajax json being an array instead of a single value.  The table itself still worked just fine with that value, but CSV export did not.  Ensuring it was a single value cleared it all up for me.

**Comment by k4rl85** [comment] 2015-10-07 15:24
I have used the last version of Buttons (1.0.3) and DataTables(1.10.9) and i have the same issue.
My solution is to cast the data to String for the Export.
Something like:
```"columns": [
                {
                    "data": "id",
                    "render": function ( data, type, full, meta ) {
                        if (type !== 'display') {
                            return String(data);
                        }
                        return customFoo(full, meta);
                    }
                },
                ...
```
Note: the button use 'filter' Orthogonal data type

**Comment by DataTables** [comment] 2015-10-07 15:39
Have you tried using the [nightly version](http://datatables.net/download/nightly#Buttons). It should already be fixed there.

**Comment by k4rl85** [comment] 2015-10-07 16:06
Just tried and it fix the conversion problems but introduce 2 bug.
1) csvhtml5 --> first title have an initial strange char
```
ï»¿"first_title"
```
2) excelhtml5 --> convert boolean to 0 for both true and false

i have tried on ubuntu 14.04 with Firefox 41.0.1 and Chrome 45.0.2454 with the same results

**Comment by DataTables** [comment] 2015-10-07 16:15
1) That is the UTF8 BOM. Most spreadsheets and text editors should handle it correctly. If you don't want the BOM at all - then you can change the character set - [code](https://github.com/DataTables/Buttons/blob/master/js/buttons.html5.js#L510).

2) It does convert? Can you please link to a test case.

**Comment by k4rl85** [comment] 2015-10-07 21:27
I have created a demo with the less possible noise here:
http://live.datatables.net/polagopi/1

I can't reproduce the UTF8 BOM problems and that are probably some problems with mine server(Django) but the conversion to 0 is present for the column 'Global'.
With this example the excel export give a directory instead of a file with Firefox.

**Comment by DataTables** [comment] 2015-10-08 15:16
[Committed fix](https://github.com/DataTables/Buttons/commit/172f872be76f132ec69418871dfbd87254610ec3) for the boolean issue.

Updated example: http://live.datatables.net/mocazaku/1/edit

> 3) excelhtml5 --> null and objects are convert to 0
> 4) csvhtml5 --> object are displayed as [object Object]

Objects shoudl be `[object Object]` as they effectively are turned into strings. `null` shouldn't be displayed in a database - however the output will now be `"null"` - i.e. `null+''`.

**Closed by DataTables** 2015-10-08 15:16 UTC
