### ISSUE TITLE
datatables-plugins npm package

### ISSUE THREAD

**Issue by akvadrako** [DataTables/DataTables#507] opened 2015-03-10 12:40 UTC
I have been trying to use datatables with bootstrap and webpack. So far I've only been using npm packages, which is elegant, but I realised the packages with the files I need are all out of date.

It would be nice to have a published official datatables-plugins npm package. Something like this: https://github.com/drmonty/datatables-plugins

**Comment by DataTables** [comment] 2015-03-10 13:10
Thanks for this. Going to close it as a [duplicate of this issue](https://github.com/DataTables/Plugins/issues/81). Although that doesn't directly relate to NPM it does ask about releases and Bower support. I would also bundle NPM with that when I get a chance to work on it.

**Closed by DataTables** 2015-03-10 13:10 UTC
