### ISSUE TITLE
Bug: "Uncaught TypeError: Cannot read property '_aData' of undefined" when using row reference after removing other row

### ISSUE THREAD

**Issue by hannes-landeholm** [DataTables/DataTables#566] opened 2015-06-03 19:00 UTC
Here's the steps to reproduce: http://jsbin.com/daziyuvocu/2/edit?html,css,js,output

Basically I'm using DataTables with the deferRender option for scalability. I want to support thousands of rows so disabling deferRender is not an option. The table will constantly mutate so I need to be able to reference all rows at all time and remove/update/insert etc. The option deferRender naturally makes `row-selector` referencing useless (AFAIK), but no problem, I just save the reference returned by the `add()` call.

The problem is that a `remove()` corrupts the existing row references, so an `data()` call will return `Uncaught TypeError: Cannot read property '_aData' of undefined`. I assume this is a bug since the documentation doesn't mention anything about it. Workarounds welcome.

**Comment by DataTables** [comment] 2015-06-03 19:30
Very interesting - thank you for the clear and concise test case!

You are correct that the issue is with the remove changing the row indexes. Because `row2` has saved a row index, and it doesn't know that the row has been removed, its held index is now wrong!

I'm currently looking at implementing a new why of handling ids in DataTables which might be quite useful for such a use case (assuming each row has a unique identifier), but that is a work in progress.

Until then, you can use `row-selector`, but you can't have it using any of the DOM interfaces. So for example you have have it using a function: http://jsbin.com/jugipohaho/1/edit?js,output .

That is currently the best workaround I can think of  - let me think some more on it.

**Comment by hannes-landeholm** [comment] 2015-06-03 20:18
Thank you for the quick reply.

>I'm currently looking at implementing a new why of handling ids in DataTables which might be quite useful for such a use case (assuming each row has a unique identifier), but that is a work in progress.

Yes, this is exactly it. I was supprised this was not currently possible.

The only problem with this workaround is that be easiest way for me to implement it (without rewriting all of my code to use function refencing instead) is to "fix" all existing references I have after a remove. This taking linear time O(n) is okay, but if I have to do it with the function solution for ever reference I have it will take O(n^2) time which is unacceptable (1000000 calls for 1000 rows). Is it somehow possible to iterate through all rows and save the row reference directly in the callback? Can I use the "idx" argument for this?

**Comment by DataTables** [comment] 2015-06-04 10:38
Yes, all existing references would either need to be refreshed, of you would just get the reference at the point of need.

Given that you would have multiple instances referring to different indexes, there isn't a way to update them all, since they are independent.

One possibility is to have DataTables not delete items from its internal data array and instead make it a sparse array. The other option is to use an object rather than an array and use the row id as the parameter key. The latter is probably the better option as I might be able to implement it alongside the existing implementation.

**Comment by hannes-landeholm** [comment] 2015-06-04 13:16
This is my O(n) workaround for now. I simply used the row index, all_rows is my own external index:

    // Repairs all row references, this is done by iterating through all rows with
    // a row selector and generating a new row reference from the numeric index.
    // This is a workaround for https://github.com/DataTables/DataTables/issues/566
    var reapirRowReferences = function() {
        dtable.rows(function(idx, data, node) {
            all_rows[data.cls][data.id] = dtable.row(idx);
            return false;
        });
    };

**Comment by DataTables** [comment] 2015-06-04 14:33
I've just [committed](https://github.com/DataTables/DataTablesSrc/commit/7d7d122d8471c8) the ability to set the id source (`rowId`) and two methods to read it (`rows().ids()` and `row().id()`). This is in the nightly now.

To use, you would store the row id as a reference and then use that as the selector.

Where than currently falls down is that the id selector will not work with deferred rendering. I think I can address than and also speed row selection by id by adding a mapping table (and the expense of a bit more memory for the map). I hope that have that in for 1.10.8.

**Comment by DataTables** [comment] 2015-07-06 20:04
Latest update - I've [added a commit](https://github.com/DataTables/DataTablesSrc/commit/bbf60cb061faa) that allows the id selectors to work even on rows that do not yet have their DOM elements created. The implementation is a simple lookup object, so it is very fast. A few more details in the commit if you are interested.

Will be included in the 1.10.8 release which will be within the next few weeks.

**Closed by DataTables** 2015-07-06 20:04 UTC

**Comment by hannes-landeholm** [comment] 2015-07-09 12:41
Nice work. I will probably try it when I get back to table UI work.

**Comment by DerDu** [comment] 2016-08-29 22:32
This is again an issue 1.10.12 ;)

**Comment by DataTables** [comment] 2016-08-30 09:40
@DerDu - Please link to a test case showing the issue.
